### ISSUE TITLE
Latest nengo_ocl release does not support latest nengo release

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_ocl#127]
I'm getting
```
Traceback (most recent call last):
  File "sparat/model/model.py", line 324, in <module>
    trial.run(**params)
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/lib/python3.5/site-packages/pytry/trial.py", line 76, in run
    result = self.execute_trial(p, plt)
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/lib/python3.5/site-packages/pytry/nengo.py", line 38, in execute_trial
    sim = Simulator(model, dt=p.dt)
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/lib/python3.5/site-packages/nengo_ocl/simulator.py", line 286, in __init__
    nengo.__version__))
ValueError: This simulator only supports Nengo 2.1.x (got 2.2.0)
```
with Nengo OCL 1.0.0 and Nengo 2.2.0.

(Independent of whether it is actually incompatible, I would prefer a warning instead of a hard failure.)

**Comment by hunse** [comment]
Yeah, `nengo_ocl` for Nengo 2.2.0 hasn't been released yet. We've also switched to warnings. You can use `nengo_ocl` master with Nengo 2.2.0.

**Comment by jgosmann** [comment]
I can't because I want to get dependencies installed automatically from PyPI. (I pinnend the Nengo version to 2.1.0 instead.)
