### ISSUE TITLE
Assert fails because function might be equal, but not identical

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_ocl#136]
I'm trying to run a model with most of the ensembles converted to direct mode, but get an `AssertionError`. This does not happen when using LIF neurons or using direct mode and the reference backend.

```
/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/pyopencl/cffi_cl.py:1476: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
Traceback (most recent call last):
  File "/home/jgosmann/gosmann-frontiers2017/psy-work/time_nback/time_nback:process:40.py", line 16, in <module>
    Worker(store=task.store).start(execute, '/home/jgosmann/gosmann-frontiers2017/psy-work/time_nback/in/40.npz', '/home/jgosmann/gosmann-frontiers2017/psy-work/time_nback/out/40.npz')
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/psyrun/backend/distribute.py", line 294, in start
    return_data=False)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/psyrun/mapper.py", line 98, in map_pspace_hdd_backed
    store.append(filename, dict_concat((get_result(fn, p),)))
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/psyrun/mapper.py", line 36, in get_result
    result.update(fn(**params))
  File "/home/jgosmann/gosmann-frontiers2017/psy-tasks/task_time_nback.py", line 32, in execute
    return benchmark_time(model, backend)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/gosmann_frontiers2017/benchmarks/benchmark.py", line 153, in benchmark_time
    sim = Simulator(model)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/gosmann_frontiers2017/backends.py", line 53, in <lambda>
    return lambda model: nengo_ocl.Simulator(model, context=context)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/nengo_ocl/simulator.py", line 293, in __init__
    self._plan.extend(self.plan_op_group(op_type, op_list))
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/nengo_ocl/simulator.py", line 562, in plan_op_group
    return getattr(self, 'plan_' + op_type.__name__)(ops)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2017/lib/python3.4/site-packages/nengo_ocl/simulator.py", line 667, in plan_SimPyFunc
    assert all(op.fn is fn for op in group)
AssertionError
```

Environment:
python 3.4.2
nengo 2.2.0
nengo-ocl 1.2.0
numpy 1.12.0
pyopencl 2016.2.1

**Comment by jgosmann** [comment]
A simpler model (circular convolution) works fine in direct mode with Nengo OCL.

**Comment by jgosmann** [comment]
I think the cause of the problem is that `groupby` uses equality to compare the functions whereas the `is` in the `assert` requires identical object IDs.

**Comment by jgosmann** [comment]
[I think the `is` should be replaced by `==` in the `assert`?](http://stackoverflow.com/questions/18216597/how-should-functions-be-tested-for-equality-or-identity)
