### ISSUE TITLE
Functools.partial has no attribute 'den'

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_ocl#80]
Got this error running the latest commit on the master branch (9d4ff91d3b):

```
Traceback (most recent call last):
  File "run_spaun.py", line 203, in <module>
    sim = nengo_ocl.sim_ocl.Simulator(model, dt=cfg.sim_dt, context=ctx)
  File "/home/abruser/git/nengo_ocl/nengo_ocl/sim_ocl.py", line 65, in __init__
    self, network=network, dt=dt, seed=seed, model=model)
  File "/home/abruser/git/nengo_ocl/nengo_ocl/sim_npy.py", line 429, in __init__
    self._plan.extend(self.plan_op_group(op_type, op_list))
  File "/home/abruser/git/nengo_ocl/nengo_ocl/sim_npy.py", line 439, in plan_op_group
    return getattr(self, 'plan_' + op_type.__name__)(ops)
  File "/home/abruser/git/nengo_ocl/nengo_ocl/sim_ocl.py", line 266, in plan_SimSynapse
    A = self.RaggedArray([f.den for f in steps])
AttributeError: 'functools.partial' object has no attribute 'den'
```

This was with trying to run Spaun 2.0 with opencl. I was previously on the ```processes``` branch and everything built fine there.

**Comment by xchoo** [comment]
Works with updated nengo.
